"""Database changes

Revision ID: 02029bab501f
Revises: 467dc45bb6e3
Create Date: 2023-08-16 14:38:40.713571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02029bab501f'
down_revision = '467dc45bb6e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MBTI_data')
    op.add_column('kakao_chatbot_dream', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('kakao_chatbot_user', sa.Column('mode', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kakao_chatbot_user', 'mode')
    op.drop_column('kakao_chatbot_dream', 'is_deleted')
    op.create_table('MBTI_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_text', mysql.TEXT(), nullable=False),
    sa.Column('mbti_resolution', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
