"""Database changes

Revision ID: 0a43e5eba695
Revises: 57c5ad51365c
Create Date: 2023-11-26 15:18:28.699450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a43e5eba695'
down_revision = '57c5ad51365c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
