"""Database changes

Revision ID: 0b515d647c08
Revises: c59ef8c8c85c
Create Date: 2023-12-07 11:04:10.476133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b515d647c08'
down_revision = 'c59ef8c8c85c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
