"""Database changes

Revision ID: 0b60b16f878b
Revises: cfc03f23343d
Create Date: 2023-05-14 16:19:09.084420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b60b16f878b'
down_revision = 'cfc03f23343d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
