"""Database changes

Revision ID: 0c238bbe75e9
Revises: dc0d6bd33a85
Create Date: 2023-10-31 14:40:08.280543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c238bbe75e9'
down_revision = 'dc0d6bd33a85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
