"""Database changes

Revision ID: 15f03971a209
Revises: 4831d58f5875
Create Date: 2023-11-05 16:20:35.785546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f03971a209'
down_revision = '4831d58f5875'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApiRequestLog', sa.Column('User_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ApiRequestLog_User_id'), 'ApiRequestLog', ['User_id'], unique=False)
    op.create_foreign_key(None, 'ApiRequestLog', 'User', ['User_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ApiRequestLog', type_='foreignkey')
    op.drop_index(op.f('ix_ApiRequestLog_User_id'), table_name='ApiRequestLog')
    op.drop_column('ApiRequestLog', 'User_id')
    # ### end Alembic commands ###
