"""Database changes

Revision ID: 1c497e15c56a
Revises: 78ff3204dfe4
Create Date: 2023-11-29 22:27:08.652627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c497e15c56a'
down_revision = '78ff3204dfe4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('error_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dashboard', 'error_count')
    # ### end Alembic commands ###
