"""Database changes

Revision ID: 1d617c8f2685
Revises: bc24fec43bf6
Create Date: 2023-06-27 15:06:17.560448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d617c8f2685'
down_revision = 'bc24fec43bf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('language_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'language_id')
    # ### end Alembic commands ###
