"""Database changes

Revision ID: 24993ec7950a
Revises: a8d3d326acab
Create Date: 2023-10-31 14:17:48.808345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24993ec7950a'
down_revision = 'a8d3d326acab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Report', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.create_index(op.f('ix_Report_is_deleted'), 'Report', ['is_deleted'], unique=False)
    op.add_column('User', sa.Column('Oauth_from', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'Oauth_from')
    op.drop_index(op.f('ix_Report_is_deleted'), table_name='Report')
    op.alter_column('Report', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
