"""Database changes

Revision ID: 27097e98ace8
Revises: 5d840fb5b761
Create Date: 2023-11-01 22:44:43.823325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27097e98ace8'
down_revision = '5d840fb5b761'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('today_luck', sa.Boolean(), nullable=True))
    op.add_column('User', sa.Column('today_history', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'today_history')
    op.drop_column('User', 'today_luck')
    # ### end Alembic commands ###
