"""Database changes

Revision ID: 272b90580245
Revises: da85a3797a8b
Create Date: 2024-01-04 10:49:29.694388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272b90580245'
down_revision = 'da85a3797a8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MorningDiary', sa.Column('is_shared', sa.Boolean(), nullable=True))
    op.add_column('MorningDiary', sa.Column('share_id', sa.String(length=255), nullable=True))
    op.add_column('NightDiary', sa.Column('is_shared', sa.Boolean(), nullable=True))
    op.add_column('NightDiary', sa.Column('share_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NightDiary', 'share_id')
    op.drop_column('NightDiary', 'is_shared')
    op.drop_column('MorningDiary', 'share_id')
    op.drop_column('MorningDiary', 'is_shared')
    # ### end Alembic commands ###
