"""Database changes

Revision ID: 2a6ccb80f2ba
Revises: 900ff9af0b3d
Create Date: 2023-05-07 17:26:18.615596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6ccb80f2ba'
down_revision = '900ff9af0b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
