"""Database changes

Revision ID: 2a8229ab06b6
Revises: 84aff0fbaf1b
Create Date: 2023-11-20 13:34:06.182291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8229ab06b6'
down_revision = '84aff0fbaf1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
