"""Database changes

Revision ID: 2cec6e842b14
Revises: 38547a4d2549
Create Date: 2023-11-29 11:21:52.674488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cec6e842b14'
down_revision = '38547a4d2549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('last_active_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'last_active_date')
    # ### end Alembic commands ###
