"""Database changes

Revision ID: 2f86c0654229
Revises: 5b516ff5f0e0
Create Date: 2024-02-09 08:18:42.553134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f86c0654229'
down_revision = '5b516ff5f0e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PushQuestion', sa.Column('is_pushed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_PushQuestion_is_pushed'), 'PushQuestion', ['is_pushed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PushQuestion_is_pushed'), table_name='PushQuestion')
    op.drop_column('PushQuestion', 'is_pushed')
    # ### end Alembic commands ###
