"""Database changes

Revision ID: 3058630bb88a
Revises: 0b2a93c3ac88
Create Date: 2023-10-31 14:24:35.948641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3058630bb88a'
down_revision = '0b2a93c3ac88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
