"""Database changes

Revision ID: 38547a4d2549
Revises: b3cabd047ac4
Create Date: 2023-11-26 21:15:22.765101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38547a4d2549'
down_revision = 'b3cabd047ac4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
