"""Database changes

Revision ID: 3ee92ed28f3a
Revises: 15f03971a209
Create Date: 2023-11-05 21:50:43.292352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee92ed28f3a'
down_revision = '15f03971a209'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ApiRequestLog', 'User', ['User_id'], ['id'])
    op.add_column('User', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.add_column('User', sa.Column('deleted_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'deleted_date')
    op.drop_column('User', 'create_date')
    op.drop_constraint(None, 'ApiRequestLog', type_='foreignkey')
    # ### end Alembic commands ###
