"""Database changes

Revision ID: 4831d58f5875
Revises: 9e803e75ff20
Create Date: 2023-11-05 15:51:22.095480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4831d58f5875'
down_revision = '9e803e75ff20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApiRequestLog', sa.Column('request_token', sa.Integer(), nullable=False))
    op.add_column('ApiRequestLog', sa.Column('response_token', sa.Integer(), nullable=False))
    op.add_column('ApiRequestLog', sa.Column('response_time_ms', sa.Integer(), nullable=False))
    op.add_column('ApiRequestLog', sa.Column('model', sa.String(length=50), nullable=False))
    op.add_column('ApiRequestLog', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ApiRequestLog', 'create_date')
    op.drop_column('ApiRequestLog', 'model')
    op.drop_column('ApiRequestLog', 'response_time_ms')
    op.drop_column('ApiRequestLog', 'response_token')
    op.drop_column('ApiRequestLog', 'request_token')
    # ### end Alembic commands ###
