"""Database changes

Revision ID: 520c9df9dcf2
Revises: c7bf4a5d0bd8
Create Date: 2023-11-06 18:56:57.112547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520c9df9dcf2'
down_revision = 'c7bf4a5d0bd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MorningDiary', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_MorningDiary_is_completed'), 'MorningDiary', ['is_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_MorningDiary_is_completed'), table_name='MorningDiary')
    op.drop_column('MorningDiary', 'is_completed')
    # ### end Alembic commands ###
