"""Database changes

Revision ID: 5289c6a663c6
Revises: fa0e705f7fa0
Create Date: 2023-11-12 12:24:03.512446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5289c6a663c6'
down_revision = 'fa0e705f7fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ErrorLog_User_id', table_name='ErrorLog')
    op.drop_column('ErrorLog', 'User_id')
    op.add_column('MorningDiary', sa.Column('main_keyword', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MorningDiary', 'main_keyword')
    op.add_column('ErrorLog', sa.Column('User_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_ErrorLog_User_id', 'ErrorLog', ['User_id'], unique=False)
    # ### end Alembic commands ###
