"""Database changes

Revision ID: 57c5ad51365c
Revises: 755c186031c3
Create Date: 2023-11-26 15:15:31.446489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c5ad51365c'
down_revision = '755c186031c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('today_chat_user', sa.Integer(), nullable=False))
    op.add_column('Dashboard', sa.Column('today_chat_mean_request', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dashboard', 'today_chat_mean_request')
    op.drop_column('Dashboard', 'today_chat_user')
    # ### end Alembic commands ###
