"""Database changes

Revision ID: 5b516ff5f0e0
Revises: 0d19aed1ed1d
Create Date: 2024-02-09 08:17:13.695809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b516ff5f0e0'
down_revision = '0d19aed1ed1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PushQuestion', sa.Column('question_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PushQuestion', 'question_type')
    # ### end Alembic commands ###
