"""Database changes

Revision ID: 5d840fb5b761
Revises: 0c238bbe75e9
Create Date: 2023-10-31 14:57:33.036157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d840fb5b761'
down_revision = '0c238bbe75e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_LookieChat_is_deleted', table_name='LookieChat')
    op.drop_table('LookieChat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookieChat',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_LookieChat_is_deleted', 'LookieChat', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
