"""Database changes

Revision ID: 60f41d20e205
Revises: f7445e27078d
Create Date: 2024-01-03 14:06:49.173445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f41d20e205'
down_revision = 'f7445e27078d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
