"""Add subscription_payment column to Diary table

Revision ID: 6b7d6e9aa30b
Revises: a5450cc63195
Create Date: 2023-05-02 16:30:12.135622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b7d6e9aa30b'
down_revision = 'a5450cc63195'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
