"""Add subscription_payment column to Diary table

Revision ID: 6b7d6e9aa30b
Revises: a5450cc63195
Create Date: 2023-05-02 16:30:12.135622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b7d6e9aa30b'
down_revision = 'a5450cc63195'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comment')
    op.add_column('Diary', sa.Column('comment_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Diary', 'comment_count')
    op.create_table('Comment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Diary_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('User_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('create_date', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Diary_id'], ['Diary.id'], name='Comment_ibfk_1'),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], name='Comment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
