"""Database changes

Revision ID: 755c186031c3
Revises: 
Create Date: 2023-11-26 14:58:09.962373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755c186031c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TextClassification', sa.Column('User_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_TextClassification_User_id'), 'TextClassification', ['User_id'], unique=False)
    op.create_foreign_key(None, 'TextClassification', 'User', ['User_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TextClassification', type_='foreignkey')
    op.drop_index(op.f('ix_TextClassification_User_id'), table_name='TextClassification')
    op.drop_column('TextClassification', 'User_id')
    # ### end Alembic commands ###
