"""Database changes

Revision ID: 78ff3204dfe4
Revises: 2cec6e842b14
Create Date: 2023-11-29 22:23:55.675146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ff3204dfe4'
down_revision = '2cec6e842b14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('dau', sa.Integer(), nullable=False))
    op.add_column('Dashboard', sa.Column('wau', sa.Integer(), nullable=False))
    op.add_column('Dashboard', sa.Column('mau', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dashboard', 'mau')
    op.drop_column('Dashboard', 'wau')
    op.drop_column('Dashboard', 'dau')
    # ### end Alembic commands ###
