"""Database changes

Revision ID: 7976acae0748
Revises: 83f196e88bad
Create Date: 2024-01-07 16:15:24.160560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7976acae0748'
down_revision = '83f196e88bad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Calendar', sa.Column('push_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Calendar', 'push_time')
    # ### end Alembic commands ###
