"""Database changes

Revision ID: 84aff0fbaf1b
Revises: b6a591c5bb68
Create Date: 2023-11-19 16:14:51.733632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84aff0fbaf1b'
down_revision = 'b6a591c5bb68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_sign_up', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_sign_up')
    # ### end Alembic commands ###
