"""Database changes

Revision ID: 900ff9af0b3d
Revises: cd913724f150
Create Date: 2023-05-07 13:17:33.703931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900ff9af0b3d'
down_revision = 'cd913724f150'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
