"""Database changes

Revision ID: 94b44629329b
Revises: e3a426153e42
Create Date: 2023-07-25 16:11:31.852714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b44629329b'
down_revision = 'e3a426153e42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kakao_chatbot_dream', sa.Column('dream_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kakao_chatbot_dream', 'dream_name')
    # ### end Alembic commands ###
