"""Database changes

Revision ID: 95944c311596
Revises: 94b44629329b
Create Date: 2023-07-26 14:51:28.547923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95944c311596'
down_revision = '94b44629329b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_chatbot_user', sa.Column('only_luck_count', sa.Integer(), nullable=False))
    op.add_column('line_chatbot_user', sa.Column('luck_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_chatbot_user', 'luck_count')
    op.drop_column('line_chatbot_user', 'only_luck_count')
    # ### end Alembic commands ###
