"""Database changes

Revision ID: 9e803e75ff20
Revises: e43f4ccc24a4
Create Date: 2023-11-05 14:57:27.763746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e803e75ff20'
down_revision = 'e43f4ccc24a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Report', sa.Column('image_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Report', 'image_url')
    # ### end Alembic commands ###
