"""Add subscription_payment column to Hot table

Revision ID: a5450cc63195
Revises: 86ff45dd409a
Create Date: 2023-05-02 11:08:02.747380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5450cc63195'
down_revision = '86ff45dd409a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Hot', sa.Column('index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Hot', 'index')
    # ### end Alembic commands ###
