"""Database changes

Revision ID: a8d3d326acab
Revises: 02029bab501f
Create Date: 2023-08-16 15:39:15.411782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d3d326acab'
down_revision = '02029bab501f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kakao_chatbot_user', sa.Column('diary_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kakao_chatbot_user', 'diary_count')
    # ### end Alembic commands ###
