"""Database changes

Revision ID: a95b20b80a30
Revises: f9f1e1e54e24
Create Date: 2023-11-12 15:59:48.041810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95b20b80a30'
down_revision = 'f9f1e1e54e24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Luck', sa.Column('is_checked', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_Luck_is_checked'), 'Luck', ['is_checked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Luck_is_checked'), table_name='Luck')
    op.drop_column('Luck', 'is_checked')
    # ### end Alembic commands ###
