"""Database changes

Revision ID: b0dada9cfa08
Revises: 4d90638fb0fe
Create Date: 2023-06-27 09:15:13.685576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0dada9cfa08'
down_revision = '4d90638fb0fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Comment', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Comment', 'Diary_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Comment', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Comment', 'comment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Comment', 'create_date',
               existing_type=mysql.VARCHAR(length=14),
               nullable=False)
    op.create_foreign_key(None, 'Comment', 'User', ['User_id'], ['id'])
    op.create_foreign_key(None, 'Comment', 'Diary', ['Diary_id'], ['id'])
    op.alter_column('Diary', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Diary', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Diary', 'dream_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Diary', 'dream',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('Diary', 'create_date',
               existing_type=mysql.VARCHAR(length=14),
               nullable=False)
    op.alter_column('Diary', 'modify_date',
               existing_type=mysql.VARCHAR(length=14),
               nullable=False)
    op.create_foreign_key(None, 'Diary', 'User', ['User_id'], ['id'])
    op.alter_column('DreamImage', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('DreamImage', 'Text_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('DreamImage', 'dream_image_url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'DreamImage', 'DreamText', ['Text_id'], ['id'])
    op.alter_column('DreamResolution', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('DreamResolution', 'Text_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('DreamResolution', 'dream_resolution',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('DreamResolution', 'today_checklist',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'DreamResolution', 'DreamText', ['Text_id'], ['id'])
    op.alter_column('DreamText', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('DreamText', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('DreamText', 'User_text',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('DreamText', 'dream_name',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('DreamText', 'dream',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('DreamText', 'DALLE2',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('DreamText', 'date',
               existing_type=mysql.VARCHAR(length=14),
               nullable=False)
    op.create_foreign_key(None, 'DreamText', 'User', ['User_id'], ['id'])
    op.alter_column('Hot', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Hot', 'index',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Hot', 'weight',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Hot', 'Diary_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Hot', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Hot', 'Diary', ['Diary_id'], ['id'])
    op.create_foreign_key(None, 'Hot', 'User', ['User_id'], ['id'])
    op.alter_column('Like', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Like', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Like', 'Diary_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Like', 'User', ['User_id'], ['id'])
    op.create_foreign_key(None, 'Like', 'Diary', ['Diary_id'], ['id'])
    op.add_column('User', sa.Column('Language', sa.String(length=10), nullable=True))
    op.alter_column('User', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('User', 'nickName',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('User', 'email',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('User', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_nickName'), 'User', ['nickName'], unique=True)
    op.alter_column('search_history', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_foreign_key(None, 'search_history', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.alter_column('search_history', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_User_nickName'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.alter_column('User', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('User', 'email',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('User', 'nickName',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('User', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('User', 'Language')
    op.drop_constraint(None, 'Like', type_='foreignkey')
    op.drop_constraint(None, 'Like', type_='foreignkey')
    op.alter_column('Like', 'Diary_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Like', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Like', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'Hot', type_='foreignkey')
    op.drop_constraint(None, 'Hot', type_='foreignkey')
    op.alter_column('Hot', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Hot', 'Diary_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Hot', 'weight',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Hot', 'index',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Hot', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'DreamText', type_='foreignkey')
    op.alter_column('DreamText', 'date',
               existing_type=mysql.VARCHAR(length=14),
               nullable=True)
    op.alter_column('DreamText', 'DALLE2',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('DreamText', 'dream',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('DreamText', 'dream_name',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('DreamText', 'User_text',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('DreamText', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('DreamText', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'DreamResolution', type_='foreignkey')
    op.alter_column('DreamResolution', 'today_checklist',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('DreamResolution', 'dream_resolution',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('DreamResolution', 'Text_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('DreamResolution', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'DreamImage', type_='foreignkey')
    op.alter_column('DreamImage', 'dream_image_url',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('DreamImage', 'Text_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('DreamImage', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'Diary', type_='foreignkey')
    op.alter_column('Diary', 'modify_date',
               existing_type=mysql.VARCHAR(length=14),
               nullable=True)
    op.alter_column('Diary', 'create_date',
               existing_type=mysql.VARCHAR(length=14),
               nullable=True)
    op.alter_column('Diary', 'dream',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('Diary', 'dream_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Diary', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Diary', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'Comment', type_='foreignkey')
    op.drop_constraint(None, 'Comment', type_='foreignkey')
    op.alter_column('Comment', 'create_date',
               existing_type=mysql.VARCHAR(length=14),
               nullable=True)
    op.alter_column('Comment', 'comment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Comment', 'User_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Comment', 'Diary_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Comment', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
