"""Database changes

Revision ID: b6a591c5bb68
Revises: a95b20b80a30
Create Date: 2023-11-19 16:04:45.256276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a591c5bb68'
down_revision = 'a95b20b80a30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_sign_up', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_sign_up')
    # ### end Alembic commands ###
