"""Database changes

Revision ID: c59ef8c8c85c
Revises: 1c497e15c56a
Create Date: 2023-12-07 11:03:41.175586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59ef8c8c85c'
down_revision = '1c497e15c56a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
