"""Database changes

Revision ID: cd913724f150
Revises: 60cc8d1eea47
Create Date: 2023-05-07 10:24:49.117896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd913724f150'
down_revision = '60cc8d1eea47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
