"""Database changes

Revision ID: cfc03f23343d
Revises: 2a6ccb80f2ba
Create Date: 2023-05-08 10:55:01.660947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc03f23343d'
down_revision = '2a6ccb80f2ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('User', sa.Column('age_range', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'age_range')
    op.drop_column('User', 'gender')
    # ### end Alembic commands ###
