"""Database changes

Revision ID: da85a3797a8b
Revises: e2b455cb8f8c
Create Date: 2024-01-03 22:15:20.201485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da85a3797a8b'
down_revision = 'e2b455cb8f8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('dau_to_mau', sa.FLOAT(), nullable=False))
    op.add_column('Dashboard', sa.Column('dau_to_wau', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dashboard', 'dau_to_wau')
    op.drop_column('Dashboard', 'dau_to_mau')
    # ### end Alembic commands ###
