"""Database changes

Revision ID: dc0d6bd33a85
Revises: 3058630bb88a
Create Date: 2023-10-31 14:27:14.841057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0d6bd33a85'
down_revision = '3058630bb88a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
