"""Database changes

Revision ID: ddff9828f7ce
Revises: 2a8229ab06b6
Create Date: 2023-11-20 13:34:12.230170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddff9828f7ce'
down_revision = '2a8229ab06b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
