"""Database changes

Revision ID: e2b455cb8f8c
Revises: 60f41d20e205
Create Date: 2024-01-03 20:10:22.460704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b455cb8f8c'
down_revision = '60f41d20e205'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dashboard', sa.Column('hdau', sa.Integer(), nullable=True))
    op.add_column('Dashboard', sa.Column('hwau', sa.Integer(), nullable=True))
    op.add_column('Dashboard', sa.Column('hmau', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dashboard', 'hmau')
    op.drop_column('Dashboard', 'hwau')
    op.drop_column('Dashboard', 'hdau')
    # ### end Alembic commands ###
