"""Database changes

Revision ID: e3a426153e42
Revises: 1d617c8f2685
Create Date: 2023-07-25 14:44:49.217227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a426153e42'
down_revision = '1d617c8f2685'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kakao_chatbot_user', sa.Column('status_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kakao_chatbot_user', 'status_score')
    # ### end Alembic commands ###
