"""Database changes

Revision ID: e43f4ccc24a4
Revises: c2d2de1b7b5e
Create Date: 2023-11-05 14:29:32.894723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43f4ccc24a4'
down_revision = 'c2d2de1b7b5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Report', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_Report_is_read'), 'Report', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Report_is_read'), table_name='Report')
    op.drop_column('Report', 'is_read')
    # ### end Alembic commands ###
