"""Database changes

Revision ID: e5384de947ec
Revises: 3ee92ed28f3a
Create Date: 2023-11-05 22:17:16.802831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5384de947ec'
down_revision = '3ee92ed28f3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Calender', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Calender', 'create_date')
    # ### end Alembic commands ###
