"""Database changes

Revision ID: f6e00ec3f6b8
Revises: 0b60b16f878b
Create Date: 2023-05-24 19:28:09.240688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e00ec3f6b8'
down_revision = '0b60b16f878b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
