"""Database changes

Revision ID: f7445e27078d
Revises: 94228c23e465
Create Date: 2024-01-03 11:57:37.338459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7445e27078d'
down_revision = '94228c23e465'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PushQuestion', sa.Column('calendar_content', sa.String(length=255), nullable=False))
    op.drop_index('ix_PushQuestion_is_deleted', table_name='PushQuestion')
    op.drop_column('PushQuestion', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PushQuestion', sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_PushQuestion_is_deleted', 'PushQuestion', ['is_deleted'], unique=False)
    op.drop_column('PushQuestion', 'calendar_content')
    # ### end Alembic commands ###
