"""Database changes

Revision ID: f9f1e1e54e24
Revises: 5289c6a663c6
Create Date: 2023-11-12 12:47:25.975405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f1e1e54e24'
down_revision = '5289c6a663c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Memo', sa.Column('tags', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Memo', 'tags')
    # ### end Alembic commands ###
