"""Database changes

Revision ID: fa0e705f7fa0
Revises: 520c9df9dcf2
Create Date: 2023-11-07 21:07:07.117708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0e705f7fa0'
down_revision = '520c9df9dcf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
