"""Database changes

Revision ID: fa0e705f7fa0
Revises: 520c9df9dcf2
Create Date: 2023-11-07 21:07:07.117708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0e705f7fa0'
down_revision = '520c9df9dcf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ErrorLog', sa.Column('User_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ErrorLog_User_id'), 'ErrorLog', ['User_id'], unique=False)
    op.create_foreign_key(None, 'ErrorLog', 'User', ['User_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ErrorLog', type_='foreignkey')
    op.drop_index(op.f('ix_ErrorLog_User_id'), table_name='ErrorLog')
    op.drop_column('ErrorLog', 'User_id')
    # ### end Alembic commands ###
